name: Build with Make

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Verify Make version
        run: make --version

      - name: Build project
        run: make
