name: Build Meowbit Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  # Initialize libopencm3

    - name: Install ARM GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make

    - name: Patch libopencm3 Makefile
      run: |
        echo "Patching libopencm3 Makefile for GitHub Actions..."
        # Force single-threaded build to avoid syntax errors
        sed -i 's|$(Q)$(MAKE) --directory=$@ SRCLIBDIR="$(SRCLIBDIR)"|$(Q)$(MAKE) -C $@ SRCLIBDIR=$(SRCLIBDIR) -j1|' libopencm3/Makefile
        # Force bash as shell globally (helps prevent /bin/sh unterminated string errors)
        sed -i '1s|^|SHELL := /bin/bash\n|' libopencm3/Makefile

    - name: Build libopencm3
      run: |
        echo "Building libopencm3 single-threaded..."
        make -C libopencm3 -j1

    - name: Build Meowbit firmware
      run: |
        echo "Building Meowbit firmware..."
        make build-bl

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: meowbit-firmware
        path: |
          build/*.hex
          build/*.bin
