name: Manual Meowbit Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo with submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Install dependencies
      - name: Setup Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi make unzip p7zip-full git

      # 3. Build libopencm3 single-threaded first
      - name: Build libopencm3
        run: |
          set -e
          echo "Building libopencm3 single-threaded to avoid syntax errors"
          make -C libopencm3 lib

      # 4. Build Meowbit firmware
      - name: Build Meowbit Firmware
        run: |
          set -e
          echo "Building Meowbit firmware..."
          make build-bl

      # 5. Package UF2
      - name: Package UF2
        shell: bash
        run: |
          if [ -f build/uf2-stm32f.zip ]; then
            echo "UF2 zip already exists"
          else
            cd build && 7z a uf2-stm32f.zip */bootloader.elf */bootloader.bin */flasher.uf2
            cd ..
          fi

      # 6. Upload artifacts
      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: meowbit-firmware
          path: |
            build/uf2-stm32f.zip
            build/*.uf2
            build/*.bin
