name: Build Meowbit Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  # Make sure libopencm3 is initialized

    - name: Set up ARM GCC
      uses: ArmMbed/mbed-action-setup-arm-gcc@v1
      with:
        version: '12-2023-q4-major' # Update if you want another GCC version

    - name: Fix libopencm3 Makefile for GitHub Actions
      run: |
        echo "Patching libopencm3 Makefile to avoid unterminated string errors..."
        sed -i 's|$(Q)$(MAKE) --directory=$@ SRCLIBDIR="$(SRCLIBDIR)"|$(Q)$(MAKE) -C $@ SRCLIBDIR=$(SRCLIBDIR)|' libopencm3/Makefile

    - name: Build libopencm3
      run: |
        echo "Building libopencm3..."
        make -C libopencm3

    - name: Build Meowbit firmware
      run: |
        echo "Building Meowbit firmware..."
        make build-bl

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: meowbit-firmware
        path: |
          build/*.hex
          build/*.bin
