name: Build Meowbit Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc-arm-none-eabi git bzip2 curl

    - name: Force bash for libopencm3 build
      run: |
        echo "Building libopencm3 single-threaded with bash"
        cd libopencm3
        MAKEFLAGS= make -j1 SHELL=/bin/bash

    - name: Build Meowbit firmware
      run: |
        echo "Building Meowbit firmware"
        make build-bl SHELL=/bin/bash

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: Meowbit-Firmware
        path: Meowbit-Firmware/build/*.hex
