name: Build Meowbit Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  # auto-init submodules

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make gcc-arm-none-eabi libnewlib-arm-none-eabi

    - name: Limit libopencm3 parallel build globally
      run: |
        export MAKEFLAGS="-j1"
        echo "Single-threaded build enabled to avoid syntax errors"

    - name: Build libopencm3
      run: |
        set -e
        echo "Building libopencm3 single-threaded..."
        make -C libopencm3 lib

    - name: Build Meowbit firmware
      run: |
        set -e
        echo "Building Meowbit firmware..."
        make build-bl

    - name: Package UF2 artifact
      run: |
        set -e
        mkdir -p release
        # adjust this path if your Makefile generates .uf2 elsewhere
        cp build/*/*.uf2 release/ || echo "No UF2 generated"
    
    - name: Upload UF2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: meowbit-firmware
        path: release/*.uf2
