name: Manual Meowbit Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo and submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Install required packages
      - name: Setup Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi make unzip p7zip-full git

      # 3. Build Meowbit firmware
      - name: Build Meowbit Firmware
        shell: bash
        run: |
          set -e
          echo "Forcing single-threaded libopencm3 build to avoid syntax errors"
          export MAKEFLAGS="-j1"
          echo "Running make build-bl..."
          make build-bl

      # 4. Package UF2 if needed
      - name: Package UF2
        shell: bash
        run: |
          if [ -f build/uf2-stm32f.zip ]; then
            echo "UF2 zip already exists"
          else
            cd build && 7z a uf2-stm32f.zip */bootloader.elf */bootloader.bin */flasher.uf2
            cd ..
          fi

      # 5. Upload firmware artifacts
      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: meowbit-firmware
          path: |
            build/uf2-stm32f.zip
            build/*.uf2
            build/*.bin

