name: Build Meowbit Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install ARM GCC toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make gcc-arm-none-eabi libnewlib-arm-none-eabi

    - name: Force single-threaded libopencm3 build
      shell: bash
      run: |
        export MAKEFLAGS="-j1"
        echo "Single-threaded build enabled globally"

    - name: Build libopencm3
      shell: bash
      run: |
        set -e
        echo "Building libopencm3..."
        make -C libopencm3 lib

    - name: Build Meowbit firmware
      shell: bash
      run: |
        set -e
        echo "Building Meowbit firmware..."
        make build-bl

    - name: Collect UF2 artifacts
      shell: bash
      run: |
        mkdir -p release
        find build -name '*.uf2' -exec cp {} release/ \; || echo "No UF2 files found"

    - name: Upload UF2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: meowbit-firmware
        path: release/*.uf2

