name: Build Meowbit Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y make gcc-arm-none-eabi bzip2

    - name: Patch libopencm3 Makefile
      working-directory: libopencm3
      run: |
        # Force bash for sub-make commands to avoid unterminated string issues
        sed -i 's|^\(\s*\)\$\$(MAKE) --directory=\$@ SRCLIBDIR="\$\(SRCLIBDIR\)"|\1bash -c "\$\$(MAKE) --directory=\$@ SRCLIBDIR=\$\(SRCLIBDIR\)"|' Makefile

    - name: Build libopencm3
      working-directory: libopencm3
      run: |
        set -e
        echo "Building libopencm3..."
        make -j1  # single-threaded to avoid issues

    - name: Build Meowbit Firmware
      run: |
        set -e
        echo "Building Meowbit firmware..."
        make build-bl

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: Meowbit-firmware
        path: Meowbit-Firmware/build/*.bin
