name: Manual Meowbit Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo and submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Install ARM GCC from Ubuntu packages
      - name: Setup ARM GCC via apt
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi
          arm-none-eabi-gcc --version

      # 3. Build Meowbit firmware
      - name: Build Meowbit Firmware
        shell: bash
        run: |
          set -e
          echo "Running make build-bl..."
          make build-bl

      # 4. Upload firmware artifacts
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: meowbit-firmware
          path: |
            build/uf2-stm32f.zip
            build/*.uf2
            build/*.bin

