name: Build Meowbit Firmware (Option A)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up ARM GCC Toolchain
        uses: ArmMbed/mbed-action-setup-arm-gcc@v1
        with:
          version: '14-2022-q3'  # Adjust version if needed

      - name: Fix Environment for libopencm3
        run: |
          echo "Building libopencm3 single-threaded using bash globally"
          export LC_ALL=C
          export LANG=C
          export SHELL=/bin/bash
          cd libopencm3
          make clean
          make -j1 lib

      - name: Build Meowbit Firmware
        run: |
          echo "Running make build-bl..."
          make build-bl

      - name: Package UF2 Artifact
        run: |
          echo "Packaging UF2..."
          mkdir -p artifact
          cp build/*/*.uf2 artifact/ || true

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: meowbit-firmware
          path: artifact/

